name: Tests Sample Maker

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - 5-building_construction-move-pattern-to-mask-object  # Déclenchement du workflow sur la branche temporaire

  # Permet d'exécuter le workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # these libraries enable testing on Qt on linux
      - uses: tlambert03/setup-qt-libs@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Tests
        uses: aganders3/headless-gui@v2
        with:
          run: python -m pytest -s -v --color=yes --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        if: matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
