name: Tests Sample Maker

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

  # Permet d'exécuter le workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # these libraries enable testing on Qt on linux
      - uses: tlambert03/setup-qt-libs@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Tests
        uses: aganders3/headless-gui@v2
        with:
          run: python -m pytest

      - name: Manage Test Reports
        run: |
          python ./Docs/Tools/pytest_json_to_rst.py ./Reports/Test_Report.json ./Reports/Test_Report_CI_${{ matrix.platform }}_${{ matrix.python-version }}.rst
          mv ./Reports/Monitoring.html ./Reports/Monitoring_CI_${{ matrix.platform }}_${{ matrix.python-version }}.html
        continue-on-error: true  # Permet de continuer même si cette étape échoue

      - name: Upload Test Reports as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: | 
            Reports/Test_Report_CI_*.rst
            Reports/Monitoring_CI_*.html
        continue-on-error: true  # Permet de continuer même si cette étape échoue

      - name: Upload coverage to Codecov
        if: matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.13'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
